Tast 1: Write a function to compute 5/0 and use try/except to catch the exceptions.

In [10]:
import sys

try:
    cal=5/0
except ZeroDivisionError:
    print("Division by zero is not allowed")
    
    

Division by zero is not allowed


Tast 2:Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [11]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

newList1=[]


for sub in subjects:
    for ver in range(2):
        newItem=sub+" "+verbs[ver]
        #newList1.append(newItem)
        for obj in range(2):
            newItem1=newItem+" "+objects[obj]
            newList1.append(newItem1)

#for newl in newList1:
#    for obj in range(2):
#        newItem=newl+" "+objects[obj]
#        newList2.append(newItem)

for i in newList1:
    print(i)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task 3: Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [10]:
import numpy as np

def generate_vander(temp1, n, increasing):
    
    if not increasing:
        first_matrix=np.array([x**(n-1-i) for x in temp1 for i in range(n)]).reshape(temp1.size,n)
    elif increasing:
        first_matrix=np.array([x**i for x in temp1 for i in range(n)]).reshape(temp1.size,n)
    return first_matrix
    

arr1=np.array([1,2,3,4,5])
num=3
 
print("Vander matrix with increasing value as True :")    
print(generate_vander(arr1,num,False))


print("Vander matrix with increasing value as False :")    
print(generate_vander(arr1,num,False))

Vander matrix with increasing value as True :
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
Vander matrix with increasing value as False :
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
